# Generated by Django 4.1.1 on 2023-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_family', models.CharField(max_length=100)),
                ('plant_des', models.TextField()),
            ],
        ),
    ]
